---
jobs:
- name: deploy
  plan:

  - get: release
    trigger: true
    params:
      include_source_tarball: true

  - get: common-tasks

  - task: source
    file: common-tasks/extract-release-tarball.yaml
    output_mapping: {extracted: source}

  - put: docker-repo

  - task: docker-image
    privileged: true
    file: common-tasks/webapp-docker-image.yaml
    input_mapping:
      webapp-docker-repo: docker-repo
      webapp-source: source
    params:
      AWS_ACCESS_KEY_ID: ((secrets.ecr-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((secrets.ecr-secret-access-key))

- name: test
  plan:
  - get: pull-request
    trigger: true
    version: every

  - get: common-tasks

  - aggregate:
    - task: build-docker-image
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/builder
        inputs:
          - name: pull-request
        params:
          REPOSITORY: dag/test
          CONTEXT: pull-request
        run:
          path: build
        outputs:
          - name: image

  - put: docker-repo
  - aggregate:
    - task: send-image-to-ecr
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/docker-image-resource
            tag: 'pr-227'
        inputs:
          - name: docker-repo
          - name: pull-request
          - name: image
        outputs:
          - name: docker-image
        params:
          AWS_ACCESS_KEY_ID: ((secrets.ecr-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((secrets.ecr-secret-access-key))
        run:
          path: sh
          args:
            - -ec
            - |
              jq -r '.[2] | .value' $(pwd)/pull-request/.git/resource/metadata.json > $(pwd)/pull-request/tag
              jq -n "{
                source: {
                  repository: \"$(cat docker-repo/uri)\",
                  aws_access_key_id: \"${AWS_ACCESS_KEY_ID}\",
                  aws_secret_access_key: \"${AWS_SECRET_ACCESS_KEY}\"
                },
                params: {
                  load_file: \"$(pwd)/image/image.tar\",
                  load_repository: \"dag/test\",
                  load_tag: \"latest\",
                  tag: \"$(pwd)/pull-request/tag\"
                }
              }" | /opt/resource/out docker-image
resources:
- name: common-tasks
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-common-concourse-tasks.git

- name: release
  type: github-release
  webhook_token: ((secrets.github-webhook-token))
  check_every: 24h
  source:
    owner: ((github-org))
    repository: ((github-repo))
    access_token: ((secrets.github-access-token))

- name: docker-repo
  type: ecr-repo
  source:
    name: ((app-name))
    region: ((secrets.aws-region))
    access_key_id: ((secrets.ecr-access-key-id))
    secret_access_key: ((secrets.ecr-secret-access-key))

- name: pull-request
  type: pull-request
  check_every: 10m
  webhook_token: ((secrets.github-webhook-token))
  source:
    repository: ((github-org))/((github-repo))
    access_token: ((secrets.github-access-token))

resource_types:
- name: ecr-repo
  type: docker-image
  source:
    repository: quay.io/mojanalytics/concourse-ecr-resource
    tag: v0.1.0

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
