#!/usr/bin/env python

from os.path import join
import json

from moj_analytics.concourse import Resource

from common import get_all, get_org, pushed_at


@Resource
def get_org_repos(dest_dir, source={}, version=None, params={}):
    print(f'Fetching {source["name"]} org')
    org = get_org(**source)
    with open(join(dest_dir, 'org'), 'w') as org_file:
        json.dump(org, org_file)

    print('Fetching org repos')
    repos = get_all(org['repos_url'], **source)
    with open(join(dest_dir, 'repos'), 'w') as repos_file:
        json.dump(repos, repos_file)

    print(f'{len(repos)} repos found')

    timestamps = sorted(set(map(pushed_at, repos)))

    return {'version': {'ref': timestamps[-1]}}


if __name__ == '__main__':
    get_org_repos()
