#!/usr/bin/env python
from os.path import join
import json

from moj_analytics.concourse import Resource
from common import get_org, pushed_at, get_all_repos


@Resource
def get_org_repos(dest_dir, source={}, version=None, params={}):
    print(f'Fetching {source["name"]} org', flush=True)
    org = get_org(**source)
    with open(join(dest_dir, "org"), "w") as org_file:
        json.dump(org, org_file)

    print("Fetching org repos", flush=True)
    repo_list = get_all_repos(source)
    with open(join(dest_dir, "repos"), "w") as repos_file:
        json.dump(repo_list, repos_file)

    print(f"{len(repo_list)} repos found", flush=True)

    timestamps = sorted(set(map(pushed_at, repo_list)))

    return {"version": {"ref": str(timestamps[-1])}}


if __name__ == "__main__":
    get_org_repos()
