#!/bin/sh

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# read inputs
destination=$1
payload=$(mktemp request.XXXXXX)
cat > $payload <&0

# parse parameters
GITHUB_ACCESS_TOKEN=$(jq -r '.source.access_token' < $payload)
name=$(jq -r '.source.name // ""' < $payload)
SKIP_SSL_VERIFICATION=$(jq -r '.source.skip_ssl_verification // false' < $payload)

org="${destination}/org"
repos="${destination}/repos"
echo "" > $repos

source /opt/resource/common.sh

org_version="none"

get_org $name > $org

repos_url="$(jq -r '.repos_url' < $org)?per_page=100"

get_all $repos_url > $repos

org_version=$(jq -r 'map(.pushed_at | fromdateiso8601) | sort | .[0]' < $repos)

echo "$(jq '. | length' $repos) repos found"

echo "{\"version\":{\"ref\":\"$org_version\"}}" >&3
