---
jobs:
- name: deploy
  plan:

  - get: release
    trigger: true
    params:
      include_source_tarball: true

  - get: common-tasks

  - task: lookup-source
    file: common-tasks/extract-release-tarball.yaml
    output_mapping: {extracted: lookup-source}

  - task: run-lookup-etl
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: quay.io/mojanalytics/lookup-tables-etl
          tag: latest
      inputs:
        - name: lookup-source
      run:
        path: python
        args:
          - /etl/run.py
      params:
        SOURCE_DIR: lookup-source
        AWS_ACCESS_KEY_ID: ((secrets.lookup-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((secrets.lookup-secret-access-key))

resources:
- name: common-tasks
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-common-concourse-tasks.git

- name: release
  type: github-release
  webhook_token: ((secrets.github-webhook-token))
  check_every: 24h
  source:
    owner: ((github-org))
    repository: ((github-repo))
    access_token: ((secrets.github-access-token))
