---
jobs:
- name: deploy
  plan:

  - get: release
    trigger: true
    params:
      include_source_tarball: true

  - get: common-tasks

  - task: webapp-source
    file: common-tasks/extract-release-tarball.yaml

  - put: webapp-docker-repo

  - task: webapp-docker-image
    privileged: true
    file: common-tasks/webapp-docker-image.yaml
    params:
      AWS_ACCESS_KEY_ID: ((secrets.ecr-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((secrets.ecr-secret-access-key))

  - put: webapp-auth0-client

  - put: webapp-helm-release
    params:
      chart: mojanalytics/webapp
      values:
      - webapp-auth0-client/credentials.yaml
      override_values:
      - { key: WebApp.Name, value: ((app-name)) }
      - { key: WebApp.BaseHost, value: ((secrets.app-domain)) }
      - { key: WebApp.Image.Repository, path: webapp-docker-repo/uri }
      - { key: WebApp.Image.Tag, path: release/tag }
      - { key: WebApp.GithubRepo, value: ((app-name)) }
      - { key: CookieSecret, value: ((secrets.cookie-secret)) }

resources:
- name: common-tasks
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-common-concourse-tasks.git

- name: release
  type: github-release
  source:
    owner: ((github-org))
    repository: ((app-name))
    access_token: ((secrets.github-access-token))

- name: webapp-auth0-client
  type: auth0-client
  source:
    app-name: ((app-name))
    app-domain: ((secrets.app-domain))
    client-id: ((secrets.auth0-client-id))
    client-secret: ((secrets.auth0-client-secret))
    domain: ((secrets.auth0-domain))
    authz-url: ((secrets.auth0-authz-url))
    authz-audience: ((secrets.auth0-authz-audience))

- name: webapp-docker-repo
  type: ecr-repo
  source:
    name: ((app-name))
    region: ((secrets.aws-region))

- name: webapp-helm-release
  type: helm
  source:
    cluster_url: ((secrets.kubernetes-api-url))
    cluster_ca: ((secrets.kubernetes-ca-cert))
    helm_host: tiller-deploy.kube-system:44134
    token: ((secrets.kubernetes-token))
    namespace: apps-prod
    release: ((app-name))
    repos:
    - name: mojanalytics
      url: https://ministryofjustice.github.io/analytics-platform-helm-charts/charts

resource_types:
- name: auth0-client
  type: docker-image
  source:
    repository: quay.io/mojanalytics/concourse-auth0-resource
    tag: v0.1.0

- name: ecr-repo
  type: docker-image
  source:
    repository: quay.io/mojanalytics/concourse-ecr-resource
    tag: v0.1.0

- name: helm
  type: docker-image
  source:
    repository: quay.io/mojanalytics/concourse-helm-resource
    tag: 0.1.9
